config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'

  get '/auth/google_oauth2', as: :google_login
  get '/auth/google_oauth2/callback', to: 'sessions#create'
  get '/logout', to: 'sessions#logout'
  # get 'sessions', to: 'sessions#create'
  
  resource :user, only: [:show, :create] do 
    resources :accomplishments, only: [:index, :create], controller: 'accomplishments'
  end

  resources :trails, only: [:index, :show]
  resources :breweries, only: [:index, :show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/accomplishments_controller.rb
class AccomplishmentsController < ApplicationController
  def index
    if current_user
      stats = BackendService.accomplishments(current_user)
      @trails    = JSON.parse(stats.body, symbolize_names: true)[:data][:user][:trails]
      @breweries = JSON.parse(stats.body, symbolize_names: true)[:data][:user][:breweries]
    end
  end

  def create
    if current_user
      if params[:trail]
        response = BackendService.accomplishments_trail(params[:user_id], params[:trail][:id], params[:trail][:name])
        if response.status == 201
          redirect_back(fallback_location: root_path)
          flash.notice = "Accomplishment Added!"
        else
          flash.alert = "Something went wrong"
        end
      end
      if params[:brewery]
        response = BackendService.accomplishments_brewery(params[:user_id], params[:brewery][:id], params[:brewery][:name])
        if response.status == 201
          flash.notice = "Accomplishment Added!"
          redirect_back(fallback_location: root_path)
        else
          flash.alert = "Something went wrong"
        end
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user

  def current_user
    unless @current_user
      user = JSON.parse(BackendService.user_create_or_find(AUTH_VAL: session[:user_email], ID: session[:user_id]).body, symbolize_names: true) if session[:user_id]

      if user && user[:data] && user[:data].first.key?(:id)
        @current_user = User.new(user[:data])
      end
    end
    @current_user
  end
end

app/controllers/breweries_controller.rb
class BreweriesController < ApplicationController
  def index
    if params[:name]
      @breweries = BreweryFacade.search_breweries("/api/v1/search_breweries?name=#{params[:name]}")
      if @breweries == []
        flash.alert = "Search returned no results"
      end
    end
  end

  def show
    @brewery = BreweryFacade.show_brewery("api/v1/search_breweries/#{params[:id]}")
    if current_user
      present = JSON.parse(BackendService.accomplishments(current_user).body, symbolize_names: true)[:data][:user][:breweries].find do |brewery|
        brewery.value?(@brewery.id)
      end
      if present
        @favorite = true
      else
        @favorite = false
      end
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :current_user, except: [:create]
  after_action  :current_user, only:   [:create]

  def create
    BackendService.user_create_or_find(user_params)
    session[:user_id]    = user_params[:google_id]
    session[:user_email] = user_params[:email]
    session[:user_token] = user_params[:google_token]

    redirect_to user_path
  end

  def logout
    session.destroy
    flash[:success] = "Not all who wander are lost - JRR Tolkien"
    redirect_to root_path
  end

  private

  def auth_hash
    request.env['omniauth.auth']
  end

  def user_params
    {
      google_id: auth_hash['uid'],
      email: auth_hash['info']['email'],
      google_token: auth_hash['credentials']['token'],
      first_name: auth_hash['info']['first_name'],
      last_name: auth_hash['info']['last_name']
    }
  end
end

app/controllers/trails_controller.rb
class TrailsController < ApplicationController
  def index
    if params[:name]
      @trails = TrailFacade.search_trails("/api/v1/search_trails?search=#{params[:name]}")
      if !@trails || @trails.empty?
        redirect_back(fallback_location: root_path)
        flash.alert = "Search returned no results"
      end
    end
  end

  def show
    trail_breweries = TrailFacade.show_trail("/api/v1/search_trails/#{params[:id]}").first
    @trail = trail_breweries[0]
    @breweries = trail_breweries[1]
    if current_user
      present = JSON.parse(BackendService.accomplishments(current_user).body, symbolize_names: true)[:data][:user][:trails].find do |trail|
        trail.value?(@trail.id)
      end
      if present
        @favorite = true
      else
        @favorite = false
      end
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new; end
  
  def create; end

  def show; end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/accomplishments/index.html.erb
<div class='container text-center page-header row'>
  <div class="col-sm-4">
    <h1>Completed Trails</h1>
    <% if current_user%>
      <% @trails.each do |trail| %>
        <%= link_to trail[:name], trail_path(trail[:trail_id]) %><br>
      <% end %>
    <% end %>
  </div>
  <div class="col-sm-4">
    <h1>Breweries Visited</h1>
      <% if current_user %>
      <% @breweries.each do |brewery| %>
        <%= link_to brewery[:name], brewery_path(brewery[:brewery_id]) %><br>
      <% end %>
    <% end %>
  </div>
</div>

app/views/breweries/index.html.erb
<div class="bg-image d-flex justify-content-center align-items-center"
  style="background-image: url('https://images.unsplash.com/photo-1584225064785-c62a8b43d148?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1974&q=80');
  height: 100vh;
  padding-top: 100px;">
  <div class='text-center'>
    <div class='body'>
      <h1><p style="background-color:black;color:white;font-size:300%;font-weight:400;"> Search Breweries </p></h1>
      <%= form_with url: breweries_path, method: :get, local: true do |form| %>
        <%= form.text_field :name %>
        <%= form.submit "Find Brewery" %>
      <% end %>
      <br><br><br>

      <% if params[:name] %>
        <% @breweries.each do |brewery| %>
          <table class="table">
            <thead>
              <tr>
                <th><%=link_to brewery.name, brewery_path(brewery.id), class: "btn btn-primary btn-lg btn-block" %></th>
              </tr>
            </thead>
          </tbody>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/breweries/show.html.erb
<div class='container'>
  <div class='text-center'>
    <div class='body'>
      <h1><p style="background-color:black;color:white;font-size:200%;font-weight:400;"><%= @brewery.name %></p></h1>
      <h3>Street Address: <%= @brewery.street %></h3>
      <h3>City: <%= "#{@brewery.city}, #{@brewery.state}" %></h3>
      <h3>Phone: <%= number_to_phone(@brewery.phone, area_code: true) %></h3>
      <% unless @brewery.website == "No website on file" %>
        <h3>Website: <%= link_to "#{@brewery.website}", @brewery.website  %></h3>
      <% else %>
        <h3>Website: <%= @brewery.website %> </h3>
      <% end %>
      <br>
      <iframe
        width="600"
        height="450"
        style="border:0"
        loading="lazy"
        allowfullscreen
        referrerpolicy="no-referrer-when-downgrade"
        src=<%="https://www.google.com/maps/embed/v1/place?key=#{ENV['GOOGLE_API_KEY']}&q=#{@brewery.name.downcase.gsub(" ", "+")}" %>>
      </iframe>
      <% if current_user %>
        <h3><%= button_to "Add to Accomplishments", user_accomplishments_path, params: { user_id: current_user.id, brewery: { id: @brewery.id, name: @brewery.name } }, method: :post, disabled: @favorite  %></h3>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
</nav>
  <head>
    <title>TrailsNBrewsFe</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.3/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
  <style>
    /* Remove the navbar's default margin-bottom and rounded borders */ 
    .navbar {
      margin-bottom: 0;
      border-radius: 0;
    }
    
    /* Set height of the grid so .sidenav can be 100% (adjust as needed) */
    .row.content {height: 450px}
    
    /* Set gray background color and 100% height */
    .sidenav {
      padding-top: 20px;
      background-color: #f1f1f1;
      height: 100%;
    }
    
    /* Set black background color, white text and some padding */
    footer {
      background-color: #555;
      color: white;
      padding: 15px;
    }
    
    /* On small screens, set height to 'auto' for sidenav and grid */
    @media screen and (max-width: 767px) {
      .sidenav {
        height: auto;
        padding: 15px;
      }
      .row.content {height:auto;} 
    }
  </style>
</head>
<body>
  <nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>                        
      </button>
      <a class="navbar-brand" href="https://github.com/TrailsNBrews"><%= image_tag "trails_n_brew_logo.png", alt: "TnB Logo", style: "height:140%;width:auto;" %></a>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav">
        <li class="active"><a href=<%= root_path %>>Home</a></li>
        <li><a href=<%=trails_path%>>Trails</a></li>
        <li><a href=<%=breweries_path%>>Breweries</a></li>
        <li><a href="https://github.com/orgs/TrailsNBrews/people">Contact</a></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if current_user %>
          <li><a href=<%= logout_path %>><span class="glyphicon glyphicon-log-in"></span>Logout</a></li>
          <li><a href=<%=user_path%>>Profile</a></li>
        <% else %>
          <li><a href=<%= google_login_path %>><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
        <% end %>  
      </ul>
    </div>
  </div>
</nav>

  <body>
    
    
  <div class='text-center'>
    <% flash.each do |type, msg| %>
    <div>
      <i><h4><%= msg %></h4></i>
    </div>
    <% end %>
  </div>
    <%= yield %>
    
  </body>
</html>

app/views/trails/index.html.erb
<div class="bg-image d-flex justify-content-center align-items-center"
  style="background-image: url('https://images.unsplash.com/photo-1592859600972-1b0834d83747?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2070&q=80');
  height: 100vh;
  padding-top: 100px;">
  <div class='text-center'>
    <div class='body'>
      <h1><p style="background-color:black;color:white;font-size:300%;font-weight:400;"> Search Trails </p></h1>
      <%= form_with url: trails_path, method: :get, local: true do |form| %>
        <%= form.text_field :name %>
        <%= form.submit "Find Trails" %>
      <% end %>
      <br><br><br>

      <% if params[:name] && @trails != nil %>
        <% @trails.each do |trail| %>
          <table class="table">
            <thead>
              <tr>
                <th><%=link_to trail.name, trail_path(trail.id), class: "btn btn-primary btn-lg btn-block" %></th>
              </tr>
            </thead>
          </tbody>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/trails/show.html.erb
<div class='container text-center body'>
  <h1><p style="background-color:black;color:white;font-size:200%;font-weight:400;"><%= @trail.name %></p></h1>
</div>

<div class="container-fluid text-left">    
  <div class="row content">
    <div class="col-sm-2 sidenav">
      <h3>Closest Breweries:</h3>
      <%@breweries.each do |brewery|%>
        <p><%= link_to brewery.name, brewery_path(brewery.id), class: "btn btn-info btn-lg" %></p>
      <% end %>
    </div>
    
    <div class="col-sm-8 text-center"> 
      <h3>More info about <%= @trail.name %> here: <%= link_to "COTREX Hiking App", "https://trails.colorado.gov/trailheads/#{@trail.name.downcase.gsub(" ", "-")}-#{@trail.co_id}" %></h3>
      <hr>
      <iframe
        width="600"
        height="450"
        style="border:0"
        loading="lazy"
        allowfullscreen
        referrerpolicy="no-referrer-when-downgrade"
        src=<%="https://www.google.com/maps/embed/v1/place?key=#{ENV['GOOGLE_API_KEY']}&q=#{@trail.latitude},#{@trail.longitude}" %>>
      </iframe>
    </div>

    <div class="col-sm-2 sidenav">
      <div class="card text-center" style="width: 200px;">
        <div class="card-body">
          <h3 class="card-title">Add Trail to Accomplishments</h5>
          <%if current_user %>
            <h3><%= button_to "Add to Accomplishments", user_accomplishments_path, params: { user_id: current_user.id, trail: { id: @trail.id, name: @trail.name } }, method: :post, disabled: @favorite, class: "btn btn-info btn-lg" %></h3>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class='container'>
  <div class='text-center'>
    <div class='page-header'>
      <h1> USER </h1>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<h1> Create New User </h1>

app/views/users/show.html.erb
<div class='container'>
  <div class='text-center'>
    <div class='page-header'>
       <h1>Welcome!</h1> 
     <% if current_user%>
       <h2><%= current_user.first_name%></h2>     
       <% end%>
  
        <%= button_to "Find Trail", trails_path, method: :get %>
        <%= button_to "Find Brewery", breweries_path, method: :get %>
        <%= button_to "Accomplishments", user_accomplishments_path, method: :get %>
       </div>
  </div>
</div>

app/views/welcome/index.html.erb
<div class="bg-image d-flex justify-content-center align-items-center"
  style="background-image: url('https://images.unsplash.com/photo-1605196560547-b2f7281b7355?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2070&q=80');
  height: 100vh;
  padding-top: 100px;">
  <div class='text-center'>
    <div class='body'>
      <h1><p style="color:white;font-size:500%;font-weight:400;text-shadow:7px 7px 7px #666;"> Trails N' Brews </p></h1>
    </div>
  </div>
</div>